// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"backend/service-platform/app/internal/auth/entities"
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSessionRepository creates a new instance of MockSessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionRepository {
	mock := &MockSessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionRepository is an autogenerated mock type for the SessionRepository type
type MockSessionRepository struct {
	mock.Mock
}

type MockSessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionRepository) EXPECT() *MockSessionRepository_Expecter {
	return &MockSessionRepository_Expecter{mock: &_m.Mock}
}

// DeleteByID provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) DeleteByID(ctx context.Context, id uuid.UUID) (*entity.Session, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByID")
	}

	var r0 *entity.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Session, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Session); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionRepository_DeleteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByID'
type MockSessionRepository_DeleteByID_Call struct {
	*mock.Call
}

// DeleteByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockSessionRepository_Expecter) DeleteByID(ctx interface{}, id interface{}) *MockSessionRepository_DeleteByID_Call {
	return &MockSessionRepository_DeleteByID_Call{Call: _e.mock.On("DeleteByID", ctx, id)}
}

func (_c *MockSessionRepository_DeleteByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockSessionRepository_DeleteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepository_DeleteByID_Call) Return(session *entity.Session, err error) *MockSessionRepository_DeleteByID_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockSessionRepository_DeleteByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*entity.Session, error)) *MockSessionRepository_DeleteByID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByUserID provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) DeleteByUserID(ctx context.Context, userID uuid.UUID) ([]entity.Session, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByUserID")
	}

	var r0 []entity.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]entity.Session, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []entity.Session); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionRepository_DeleteByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByUserID'
type MockSessionRepository_DeleteByUserID_Call struct {
	*mock.Call
}

// DeleteByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockSessionRepository_Expecter) DeleteByUserID(ctx interface{}, userID interface{}) *MockSessionRepository_DeleteByUserID_Call {
	return &MockSessionRepository_DeleteByUserID_Call{Call: _e.mock.On("DeleteByUserID", ctx, userID)}
}

func (_c *MockSessionRepository_DeleteByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockSessionRepository_DeleteByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepository_DeleteByUserID_Call) Return(sessions []entity.Session, err error) *MockSessionRepository_DeleteByUserID_Call {
	_c.Call.Return(sessions, err)
	return _c
}

func (_c *MockSessionRepository_DeleteByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) ([]entity.Session, error)) *MockSessionRepository_DeleteByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByToken provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) FindByToken(ctx context.Context, token string) (*entity.Session, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for FindByToken")
	}

	var r0 *entity.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.Session, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.Session); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionRepository_FindByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByToken'
type MockSessionRepository_FindByToken_Call struct {
	*mock.Call
}

// FindByToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockSessionRepository_Expecter) FindByToken(ctx interface{}, token interface{}) *MockSessionRepository_FindByToken_Call {
	return &MockSessionRepository_FindByToken_Call{Call: _e.mock.On("FindByToken", ctx, token)}
}

func (_c *MockSessionRepository_FindByToken_Call) Run(run func(ctx context.Context, token string)) *MockSessionRepository_FindByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepository_FindByToken_Call) Return(session *entity.Session, err error) *MockSessionRepository_FindByToken_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockSessionRepository_FindByToken_Call) RunAndReturn(run func(ctx context.Context, token string) (*entity.Session, error)) *MockSessionRepository_FindByToken_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) Insert(ctx context.Context, session *entity.Session) (*entity.Session, error) {
	ret := _mock.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 *entity.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Session) (*entity.Session, error)); ok {
		return returnFunc(ctx, session)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Session) *entity.Session); ok {
		r0 = returnFunc(ctx, session)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.Session) error); ok {
		r1 = returnFunc(ctx, session)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockSessionRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - session *entity.Session
func (_e *MockSessionRepository_Expecter) Insert(ctx interface{}, session interface{}) *MockSessionRepository_Insert_Call {
	return &MockSessionRepository_Insert_Call{Call: _e.mock.On("Insert", ctx, session)}
}

func (_c *MockSessionRepository_Insert_Call) Run(run func(ctx context.Context, session *entity.Session)) *MockSessionRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Session
		if args[1] != nil {
			arg1 = args[1].(*entity.Session)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepository_Insert_Call) Return(session1 *entity.Session, err error) *MockSessionRepository_Insert_Call {
	_c.Call.Return(session1, err)
	return _c
}

func (_c *MockSessionRepository_Insert_Call) RunAndReturn(run func(ctx context.Context, session *entity.Session) (*entity.Session, error)) *MockSessionRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeByToken provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) RevokeByToken(ctx context.Context, token string) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for RevokeByToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_RevokeByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeByToken'
type MockSessionRepository_RevokeByToken_Call struct {
	*mock.Call
}

// RevokeByToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockSessionRepository_Expecter) RevokeByToken(ctx interface{}, token interface{}) *MockSessionRepository_RevokeByToken_Call {
	return &MockSessionRepository_RevokeByToken_Call{Call: _e.mock.On("RevokeByToken", ctx, token)}
}

func (_c *MockSessionRepository_RevokeByToken_Call) Run(run func(ctx context.Context, token string)) *MockSessionRepository_RevokeByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepository_RevokeByToken_Call) Return(err error) *MockSessionRepository_RevokeByToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_RevokeByToken_Call) RunAndReturn(run func(ctx context.Context, token string) error) *MockSessionRepository_RevokeByToken_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeByUserID provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) RevokeByUserID(ctx context.Context, userID uuid.UUID) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeByUserID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_RevokeByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeByUserID'
type MockSessionRepository_RevokeByUserID_Call struct {
	*mock.Call
}

// RevokeByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockSessionRepository_Expecter) RevokeByUserID(ctx interface{}, userID interface{}) *MockSessionRepository_RevokeByUserID_Call {
	return &MockSessionRepository_RevokeByUserID_Call{Call: _e.mock.On("RevokeByUserID", ctx, userID)}
}

func (_c *MockSessionRepository_RevokeByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockSessionRepository_RevokeByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepository_RevokeByUserID_Call) Return(err error) *MockSessionRepository_RevokeByUserID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_RevokeByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) error) *MockSessionRepository_RevokeByUserID_Call {
	_c.Call.Return(run)
	return _c
}
