// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"backend/service-platform/app/internal/auth/entities"
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// DeleteByID provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) DeleteByID(ctx context.Context, id uuid.UUID) (*entity.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByID")
	}

	var r0 *entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_DeleteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByID'
type MockUserRepository_DeleteByID_Call struct {
	*mock.Call
}

// DeleteByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUserRepository_Expecter) DeleteByID(ctx interface{}, id interface{}) *MockUserRepository_DeleteByID_Call {
	return &MockUserRepository_DeleteByID_Call{Call: _e.mock.On("DeleteByID", ctx, id)}
}

func (_c *MockUserRepository_DeleteByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUserRepository_DeleteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_DeleteByID_Call) Return(user *entity.User, err error) *MockUserRepository_DeleteByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_DeleteByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*entity.User, error)) *MockUserRepository_DeleteByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindActiveUserByUsername provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) FindActiveUserByUsername(ctx context.Context, username string) (*entity.User, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for FindActiveUserByUsername")
	}

	var r0 *entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.User, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.User); ok {
		r0 = returnFunc(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_FindActiveUserByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindActiveUserByUsername'
type MockUserRepository_FindActiveUserByUsername_Call struct {
	*mock.Call
}

// FindActiveUserByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockUserRepository_Expecter) FindActiveUserByUsername(ctx interface{}, username interface{}) *MockUserRepository_FindActiveUserByUsername_Call {
	return &MockUserRepository_FindActiveUserByUsername_Call{Call: _e.mock.On("FindActiveUserByUsername", ctx, username)}
}

func (_c *MockUserRepository_FindActiveUserByUsername_Call) Run(run func(ctx context.Context, username string)) *MockUserRepository_FindActiveUserByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_FindActiveUserByUsername_Call) Return(user *entity.User, err error) *MockUserRepository_FindActiveUserByUsername_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_FindActiveUserByUsername_Call) RunAndReturn(run func(ctx context.Context, username string) (*entity.User, error)) *MockUserRepository_FindActiveUserByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmail provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) FindByEmail(ctx context.Context, email string) (*entity.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 *entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type MockUserRepository_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserRepository_Expecter) FindByEmail(ctx interface{}, email interface{}) *MockUserRepository_FindByEmail_Call {
	return &MockUserRepository_FindByEmail_Call{Call: _e.mock.On("FindByEmail", ctx, email)}
}

func (_c *MockUserRepository_FindByEmail_Call) Run(run func(ctx context.Context, email string)) *MockUserRepository_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_FindByEmail_Call) Return(user *entity.User, err error) *MockUserRepository_FindByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_FindByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*entity.User, error)) *MockUserRepository_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) FindByID(ctx context.Context, id uuid.UUID) (*entity.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockUserRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUserRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockUserRepository_FindByID_Call {
	return &MockUserRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockUserRepository_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUserRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_FindByID_Call) Return(user *entity.User, err error) *MockUserRepository_FindByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*entity.User, error)) *MockUserRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByPhoneNumber provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) FindByPhoneNumber(ctx context.Context, phoneNumber string) (*entity.User, error) {
	ret := _mock.Called(ctx, phoneNumber)

	if len(ret) == 0 {
		panic("no return value specified for FindByPhoneNumber")
	}

	var r0 *entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.User, error)); ok {
		return returnFunc(ctx, phoneNumber)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.User); ok {
		r0 = returnFunc(ctx, phoneNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, phoneNumber)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_FindByPhoneNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByPhoneNumber'
type MockUserRepository_FindByPhoneNumber_Call struct {
	*mock.Call
}

// FindByPhoneNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - phoneNumber string
func (_e *MockUserRepository_Expecter) FindByPhoneNumber(ctx interface{}, phoneNumber interface{}) *MockUserRepository_FindByPhoneNumber_Call {
	return &MockUserRepository_FindByPhoneNumber_Call{Call: _e.mock.On("FindByPhoneNumber", ctx, phoneNumber)}
}

func (_c *MockUserRepository_FindByPhoneNumber_Call) Run(run func(ctx context.Context, phoneNumber string)) *MockUserRepository_FindByPhoneNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_FindByPhoneNumber_Call) Return(user *entity.User, err error) *MockUserRepository_FindByPhoneNumber_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_FindByPhoneNumber_Call) RunAndReturn(run func(ctx context.Context, phoneNumber string) (*entity.User, error)) *MockUserRepository_FindByPhoneNumber_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUsername provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) FindByUsername(ctx context.Context, username string) (*entity.User, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for FindByUsername")
	}

	var r0 *entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.User, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.User); ok {
		r0 = returnFunc(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_FindByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUsername'
type MockUserRepository_FindByUsername_Call struct {
	*mock.Call
}

// FindByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockUserRepository_Expecter) FindByUsername(ctx interface{}, username interface{}) *MockUserRepository_FindByUsername_Call {
	return &MockUserRepository_FindByUsername_Call{Call: _e.mock.On("FindByUsername", ctx, username)}
}

func (_c *MockUserRepository_FindByUsername_Call) Run(run func(ctx context.Context, username string)) *MockUserRepository_FindByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_FindByUsername_Call) Return(user *entity.User, err error) *MockUserRepository_FindByUsername_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_FindByUsername_Call) RunAndReturn(run func(ctx context.Context, username string) (*entity.User, error)) *MockUserRepository_FindByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) Insert(ctx context.Context, user *entity.User) (*entity.User, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 *entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.User) (*entity.User, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.User) *entity.User); ok {
		r0 = returnFunc(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockUserRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - user *entity.User
func (_e *MockUserRepository_Expecter) Insert(ctx interface{}, user interface{}) *MockUserRepository_Insert_Call {
	return &MockUserRepository_Insert_Call{Call: _e.mock.On("Insert", ctx, user)}
}

func (_c *MockUserRepository_Insert_Call) Run(run func(ctx context.Context, user *entity.User)) *MockUserRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.User
		if args[1] != nil {
			arg1 = args[1].(*entity.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_Insert_Call) Return(user1 *entity.User, err error) *MockUserRepository_Insert_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockUserRepository_Insert_Call) RunAndReturn(run func(ctx context.Context, user *entity.User) (*entity.User, error)) *MockUserRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) Update(ctx context.Context, user entity.User) (*entity.User, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.User) (*entity.User, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.User) *entity.User); ok {
		r0 = returnFunc(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUserRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - user entity.User
func (_e *MockUserRepository_Expecter) Update(ctx interface{}, user interface{}) *MockUserRepository_Update_Call {
	return &MockUserRepository_Update_Call{Call: _e.mock.On("Update", ctx, user)}
}

func (_c *MockUserRepository_Update_Call) Run(run func(ctx context.Context, user entity.User)) *MockUserRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entity.User
		if args[1] != nil {
			arg1 = args[1].(entity.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_Update_Call) Return(user1 *entity.User, err error) *MockUserRepository_Update_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockUserRepository_Update_Call) RunAndReturn(run func(ctx context.Context, user entity.User) (*entity.User, error)) *MockUserRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateEmailVerified provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) UpdateEmailVerified(ctx context.Context, userID uuid.UUID, verified bool) error {
	ret := _mock.Called(ctx, userID, verified)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEmailVerified")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) error); ok {
		r0 = returnFunc(ctx, userID, verified)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_UpdateEmailVerified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateEmailVerified'
type MockUserRepository_UpdateEmailVerified_Call struct {
	*mock.Call
}

// UpdateEmailVerified is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - verified bool
func (_e *MockUserRepository_Expecter) UpdateEmailVerified(ctx interface{}, userID interface{}, verified interface{}) *MockUserRepository_UpdateEmailVerified_Call {
	return &MockUserRepository_UpdateEmailVerified_Call{Call: _e.mock.On("UpdateEmailVerified", ctx, userID, verified)}
}

func (_c *MockUserRepository_UpdateEmailVerified_Call) Run(run func(ctx context.Context, userID uuid.UUID, verified bool)) *MockUserRepository_UpdateEmailVerified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepository_UpdateEmailVerified_Call) Return(err error) *MockUserRepository_UpdateEmailVerified_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_UpdateEmailVerified_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, verified bool) error) *MockUserRepository_UpdateEmailVerified_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateLastLoginAt provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) UpdateLastLoginAt(ctx context.Context, userID uuid.UUID) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLastLoginAt")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_UpdateLastLoginAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLastLoginAt'
type MockUserRepository_UpdateLastLoginAt_Call struct {
	*mock.Call
}

// UpdateLastLoginAt is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockUserRepository_Expecter) UpdateLastLoginAt(ctx interface{}, userID interface{}) *MockUserRepository_UpdateLastLoginAt_Call {
	return &MockUserRepository_UpdateLastLoginAt_Call{Call: _e.mock.On("UpdateLastLoginAt", ctx, userID)}
}

func (_c *MockUserRepository_UpdateLastLoginAt_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockUserRepository_UpdateLastLoginAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_UpdateLastLoginAt_Call) Return(err error) *MockUserRepository_UpdateLastLoginAt_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_UpdateLastLoginAt_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) error) *MockUserRepository_UpdateLastLoginAt_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePhoneVerified provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) UpdatePhoneVerified(ctx context.Context, userID uuid.UUID, verified bool) error {
	ret := _mock.Called(ctx, userID, verified)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePhoneVerified")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) error); ok {
		r0 = returnFunc(ctx, userID, verified)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_UpdatePhoneVerified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePhoneVerified'
type MockUserRepository_UpdatePhoneVerified_Call struct {
	*mock.Call
}

// UpdatePhoneVerified is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - verified bool
func (_e *MockUserRepository_Expecter) UpdatePhoneVerified(ctx interface{}, userID interface{}, verified interface{}) *MockUserRepository_UpdatePhoneVerified_Call {
	return &MockUserRepository_UpdatePhoneVerified_Call{Call: _e.mock.On("UpdatePhoneVerified", ctx, userID, verified)}
}

func (_c *MockUserRepository_UpdatePhoneVerified_Call) Run(run func(ctx context.Context, userID uuid.UUID, verified bool)) *MockUserRepository_UpdatePhoneVerified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepository_UpdatePhoneVerified_Call) Return(err error) *MockUserRepository_UpdatePhoneVerified_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_UpdatePhoneVerified_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, verified bool) error) *MockUserRepository_UpdatePhoneVerified_Call {
	_c.Call.Return(run)
	return _c
}
