// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"backend/service-platform/app/internal/job/entities"
	"backend/service-platform/app/internal/worker"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockJobManagerInterface creates a new instance of MockJobManagerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJobManagerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJobManagerInterface {
	mock := &MockJobManagerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJobManagerInterface is an autogenerated mock type for the JobManagerInterface type
type MockJobManagerInterface struct {
	mock.Mock
}

type MockJobManagerInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJobManagerInterface) EXPECT() *MockJobManagerInterface_Expecter {
	return &MockJobManagerInterface_Expecter{mock: &_m.Mock}
}

// CreateJob provides a mock function for the type MockJobManagerInterface
func (_mock *MockJobManagerInterface) CreateJob(ctx context.Context, req worker.CreateJobRequest) (*entity.Job, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateJob")
	}

	var r0 *entity.Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, worker.CreateJobRequest) (*entity.Job, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, worker.CreateJobRequest) *entity.Job); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, worker.CreateJobRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJobManagerInterface_CreateJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateJob'
type MockJobManagerInterface_CreateJob_Call struct {
	*mock.Call
}

// CreateJob is a helper method to define mock.On call
//   - ctx context.Context
//   - req worker.CreateJobRequest
func (_e *MockJobManagerInterface_Expecter) CreateJob(ctx interface{}, req interface{}) *MockJobManagerInterface_CreateJob_Call {
	return &MockJobManagerInterface_CreateJob_Call{Call: _e.mock.On("CreateJob", ctx, req)}
}

func (_c *MockJobManagerInterface_CreateJob_Call) Run(run func(ctx context.Context, req worker.CreateJobRequest)) *MockJobManagerInterface_CreateJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 worker.CreateJobRequest
		if args[1] != nil {
			arg1 = args[1].(worker.CreateJobRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJobManagerInterface_CreateJob_Call) Return(job *entity.Job, err error) *MockJobManagerInterface_CreateJob_Call {
	_c.Call.Return(job, err)
	return _c
}

func (_c *MockJobManagerInterface_CreateJob_Call) RunAndReturn(run func(ctx context.Context, req worker.CreateJobRequest) (*entity.Job, error)) *MockJobManagerInterface_CreateJob_Call {
	_c.Call.Return(run)
	return _c
}
