// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"backend/service-platform/app/internal/collection/entities"
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"github.com/uptrace/bun"
)

// NewMockItemRepository creates a new instance of MockItemRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItemRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItemRepository {
	mock := &MockItemRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockItemRepository is an autogenerated mock type for the ItemRepository type
type MockItemRepository struct {
	mock.Mock
}

type MockItemRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItemRepository) EXPECT() *MockItemRepository_Expecter {
	return &MockItemRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockItemRepository
func (_mock *MockItemRepository) Create(ctx context.Context, item *entity.Item) (*entity.Item, error) {
	ret := _mock.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Item) (*entity.Item, error)); ok {
		return returnFunc(ctx, item)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Item) *entity.Item); ok {
		r0 = returnFunc(ctx, item)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.Item) error); ok {
		r1 = returnFunc(ctx, item)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockItemRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockItemRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - item *entity.Item
func (_e *MockItemRepository_Expecter) Create(ctx interface{}, item interface{}) *MockItemRepository_Create_Call {
	return &MockItemRepository_Create_Call{Call: _e.mock.On("Create", ctx, item)}
}

func (_c *MockItemRepository_Create_Call) Run(run func(ctx context.Context, item *entity.Item)) *MockItemRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Item
		if args[1] != nil {
			arg1 = args[1].(*entity.Item)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockItemRepository_Create_Call) Return(item1 *entity.Item, err error) *MockItemRepository_Create_Call {
	_c.Call.Return(item1, err)
	return _c
}

func (_c *MockItemRepository_Create_Call) RunAndReturn(run func(ctx context.Context, item *entity.Item) (*entity.Item, error)) *MockItemRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockItemRepository
func (_mock *MockItemRepository) FindByID(ctx context.Context, id uuid.UUID) (*entity.Item, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Item, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Item); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockItemRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockItemRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockItemRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockItemRepository_FindByID_Call {
	return &MockItemRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockItemRepository_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockItemRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockItemRepository_FindByID_Call) Return(item *entity.Item, err error) *MockItemRepository_FindByID_Call {
	_c.Call.Return(item, err)
	return _c
}

func (_c *MockItemRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*entity.Item, error)) *MockItemRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByCollectionIDs provides a mock function for the type MockItemRepository
func (_mock *MockItemRepository) ListByCollectionIDs(ctx context.Context, collectionIDs []uuid.UUID, includeDeleted bool) ([]entity.Item, error) {
	ret := _mock.Called(ctx, collectionIDs, includeDeleted)

	if len(ret) == 0 {
		panic("no return value specified for ListByCollectionIDs")
	}

	var r0 []entity.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID, bool) ([]entity.Item, error)); ok {
		return returnFunc(ctx, collectionIDs, includeDeleted)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID, bool) []entity.Item); ok {
		r0 = returnFunc(ctx, collectionIDs, includeDeleted)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uuid.UUID, bool) error); ok {
		r1 = returnFunc(ctx, collectionIDs, includeDeleted)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockItemRepository_ListByCollectionIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByCollectionIDs'
type MockItemRepository_ListByCollectionIDs_Call struct {
	*mock.Call
}

// ListByCollectionIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - collectionIDs []uuid.UUID
//   - includeDeleted bool
func (_e *MockItemRepository_Expecter) ListByCollectionIDs(ctx interface{}, collectionIDs interface{}, includeDeleted interface{}) *MockItemRepository_ListByCollectionIDs_Call {
	return &MockItemRepository_ListByCollectionIDs_Call{Call: _e.mock.On("ListByCollectionIDs", ctx, collectionIDs, includeDeleted)}
}

func (_c *MockItemRepository_ListByCollectionIDs_Call) Run(run func(ctx context.Context, collectionIDs []uuid.UUID, includeDeleted bool)) *MockItemRepository_ListByCollectionIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockItemRepository_ListByCollectionIDs_Call) Return(items []entity.Item, err error) *MockItemRepository_ListByCollectionIDs_Call {
	_c.Call.Return(items, err)
	return _c
}

func (_c *MockItemRepository_ListByCollectionIDs_Call) RunAndReturn(run func(ctx context.Context, collectionIDs []uuid.UUID, includeDeleted bool) ([]entity.Item, error)) *MockItemRepository_ListByCollectionIDs_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDeleteByIDs provides a mock function for the type MockItemRepository
func (_mock *MockItemRepository) SoftDeleteByIDs(ctx context.Context, exec bun.IDB, ids []uuid.UUID) (int64, error) {
	ret := _mock.Called(ctx, exec, ids)

	if len(ret) == 0 {
		panic("no return value specified for SoftDeleteByIDs")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bun.IDB, []uuid.UUID) (int64, error)); ok {
		return returnFunc(ctx, exec, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bun.IDB, []uuid.UUID) int64); ok {
		r0 = returnFunc(ctx, exec, ids)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bun.IDB, []uuid.UUID) error); ok {
		r1 = returnFunc(ctx, exec, ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockItemRepository_SoftDeleteByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDeleteByIDs'
type MockItemRepository_SoftDeleteByIDs_Call struct {
	*mock.Call
}

// SoftDeleteByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - exec bun.IDB
//   - ids []uuid.UUID
func (_e *MockItemRepository_Expecter) SoftDeleteByIDs(ctx interface{}, exec interface{}, ids interface{}) *MockItemRepository_SoftDeleteByIDs_Call {
	return &MockItemRepository_SoftDeleteByIDs_Call{Call: _e.mock.On("SoftDeleteByIDs", ctx, exec, ids)}
}

func (_c *MockItemRepository_SoftDeleteByIDs_Call) Run(run func(ctx context.Context, exec bun.IDB, ids []uuid.UUID)) *MockItemRepository_SoftDeleteByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bun.IDB
		if args[1] != nil {
			arg1 = args[1].(bun.IDB)
		}
		var arg2 []uuid.UUID
		if args[2] != nil {
			arg2 = args[2].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockItemRepository_SoftDeleteByIDs_Call) Return(n int64, err error) *MockItemRepository_SoftDeleteByIDs_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockItemRepository_SoftDeleteByIDs_Call) RunAndReturn(run func(ctx context.Context, exec bun.IDB, ids []uuid.UUID) (int64, error)) *MockItemRepository_SoftDeleteByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockItemRepository
func (_mock *MockItemRepository) Update(ctx context.Context, item *entity.Item) (*entity.Item, error) {
	ret := _mock.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *entity.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Item) (*entity.Item, error)); ok {
		return returnFunc(ctx, item)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Item) *entity.Item); ok {
		r0 = returnFunc(ctx, item)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.Item) error); ok {
		r1 = returnFunc(ctx, item)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockItemRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockItemRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - item *entity.Item
func (_e *MockItemRepository_Expecter) Update(ctx interface{}, item interface{}) *MockItemRepository_Update_Call {
	return &MockItemRepository_Update_Call{Call: _e.mock.On("Update", ctx, item)}
}

func (_c *MockItemRepository_Update_Call) Run(run func(ctx context.Context, item *entity.Item)) *MockItemRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Item
		if args[1] != nil {
			arg1 = args[1].(*entity.Item)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockItemRepository_Update_Call) Return(item1 *entity.Item, err error) *MockItemRepository_Update_Call {
	_c.Call.Return(item1, err)
	return _c
}

func (_c *MockItemRepository_Update_Call) RunAndReturn(run func(ctx context.Context, item *entity.Item) (*entity.Item, error)) *MockItemRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
