// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"backend/service-platform/app/internal/collection/entities"
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"github.com/uptrace/bun"
)

// NewMockCollectionItemRepository creates a new instance of MockCollectionItemRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCollectionItemRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCollectionItemRepository {
	mock := &MockCollectionItemRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCollectionItemRepository is an autogenerated mock type for the CollectionItemRepository type
type MockCollectionItemRepository struct {
	mock.Mock
}

type MockCollectionItemRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCollectionItemRepository) EXPECT() *MockCollectionItemRepository_Expecter {
	return &MockCollectionItemRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockCollectionItemRepository
func (_mock *MockCollectionItemRepository) Create(ctx context.Context, item *entity.CollectionItem) (*entity.CollectionItem, error) {
	ret := _mock.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.CollectionItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.CollectionItem) (*entity.CollectionItem, error)); ok {
		return returnFunc(ctx, item)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.CollectionItem) *entity.CollectionItem); ok {
		r0 = returnFunc(ctx, item)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.CollectionItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.CollectionItem) error); ok {
		r1 = returnFunc(ctx, item)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCollectionItemRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCollectionItemRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - item *entity.CollectionItem
func (_e *MockCollectionItemRepository_Expecter) Create(ctx interface{}, item interface{}) *MockCollectionItemRepository_Create_Call {
	return &MockCollectionItemRepository_Create_Call{Call: _e.mock.On("Create", ctx, item)}
}

func (_c *MockCollectionItemRepository_Create_Call) Run(run func(ctx context.Context, item *entity.CollectionItem)) *MockCollectionItemRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.CollectionItem
		if args[1] != nil {
			arg1 = args[1].(*entity.CollectionItem)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCollectionItemRepository_Create_Call) Return(collectionItem *entity.CollectionItem, err error) *MockCollectionItemRepository_Create_Call {
	_c.Call.Return(collectionItem, err)
	return _c
}

func (_c *MockCollectionItemRepository_Create_Call) RunAndReturn(run func(ctx context.Context, item *entity.CollectionItem) (*entity.CollectionItem, error)) *MockCollectionItemRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockCollectionItemRepository
func (_mock *MockCollectionItemRepository) FindByID(ctx context.Context, id uuid.UUID) (*entity.CollectionItem, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.CollectionItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.CollectionItem, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.CollectionItem); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.CollectionItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCollectionItemRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockCollectionItemRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockCollectionItemRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockCollectionItemRepository_FindByID_Call {
	return &MockCollectionItemRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockCollectionItemRepository_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockCollectionItemRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCollectionItemRepository_FindByID_Call) Return(collectionItem *entity.CollectionItem, err error) *MockCollectionItemRepository_FindByID_Call {
	_c.Call.Return(collectionItem, err)
	return _c
}

func (_c *MockCollectionItemRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*entity.CollectionItem, error)) *MockCollectionItemRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByCollectionIDs provides a mock function for the type MockCollectionItemRepository
func (_mock *MockCollectionItemRepository) ListByCollectionIDs(ctx context.Context, collectionIDs []uuid.UUID, includeDeleted bool) ([]entity.CollectionItem, error) {
	ret := _mock.Called(ctx, collectionIDs, includeDeleted)

	if len(ret) == 0 {
		panic("no return value specified for ListByCollectionIDs")
	}

	var r0 []entity.CollectionItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID, bool) ([]entity.CollectionItem, error)); ok {
		return returnFunc(ctx, collectionIDs, includeDeleted)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID, bool) []entity.CollectionItem); ok {
		r0 = returnFunc(ctx, collectionIDs, includeDeleted)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.CollectionItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uuid.UUID, bool) error); ok {
		r1 = returnFunc(ctx, collectionIDs, includeDeleted)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCollectionItemRepository_ListByCollectionIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByCollectionIDs'
type MockCollectionItemRepository_ListByCollectionIDs_Call struct {
	*mock.Call
}

// ListByCollectionIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - collectionIDs []uuid.UUID
//   - includeDeleted bool
func (_e *MockCollectionItemRepository_Expecter) ListByCollectionIDs(ctx interface{}, collectionIDs interface{}, includeDeleted interface{}) *MockCollectionItemRepository_ListByCollectionIDs_Call {
	return &MockCollectionItemRepository_ListByCollectionIDs_Call{Call: _e.mock.On("ListByCollectionIDs", ctx, collectionIDs, includeDeleted)}
}

func (_c *MockCollectionItemRepository_ListByCollectionIDs_Call) Run(run func(ctx context.Context, collectionIDs []uuid.UUID, includeDeleted bool)) *MockCollectionItemRepository_ListByCollectionIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCollectionItemRepository_ListByCollectionIDs_Call) Return(collectionItems []entity.CollectionItem, err error) *MockCollectionItemRepository_ListByCollectionIDs_Call {
	_c.Call.Return(collectionItems, err)
	return _c
}

func (_c *MockCollectionItemRepository_ListByCollectionIDs_Call) RunAndReturn(run func(ctx context.Context, collectionIDs []uuid.UUID, includeDeleted bool) ([]entity.CollectionItem, error)) *MockCollectionItemRepository_ListByCollectionIDs_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDeleteByCollectionID provides a mock function for the type MockCollectionItemRepository
func (_mock *MockCollectionItemRepository) SoftDeleteByCollectionID(ctx context.Context, exec bun.IDB, collectionID uuid.UUID) (int64, error) {
	ret := _mock.Called(ctx, exec, collectionID)

	if len(ret) == 0 {
		panic("no return value specified for SoftDeleteByCollectionID")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bun.IDB, uuid.UUID) (int64, error)); ok {
		return returnFunc(ctx, exec, collectionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bun.IDB, uuid.UUID) int64); ok {
		r0 = returnFunc(ctx, exec, collectionID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bun.IDB, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, exec, collectionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCollectionItemRepository_SoftDeleteByCollectionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDeleteByCollectionID'
type MockCollectionItemRepository_SoftDeleteByCollectionID_Call struct {
	*mock.Call
}

// SoftDeleteByCollectionID is a helper method to define mock.On call
//   - ctx context.Context
//   - exec bun.IDB
//   - collectionID uuid.UUID
func (_e *MockCollectionItemRepository_Expecter) SoftDeleteByCollectionID(ctx interface{}, exec interface{}, collectionID interface{}) *MockCollectionItemRepository_SoftDeleteByCollectionID_Call {
	return &MockCollectionItemRepository_SoftDeleteByCollectionID_Call{Call: _e.mock.On("SoftDeleteByCollectionID", ctx, exec, collectionID)}
}

func (_c *MockCollectionItemRepository_SoftDeleteByCollectionID_Call) Run(run func(ctx context.Context, exec bun.IDB, collectionID uuid.UUID)) *MockCollectionItemRepository_SoftDeleteByCollectionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bun.IDB
		if args[1] != nil {
			arg1 = args[1].(bun.IDB)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCollectionItemRepository_SoftDeleteByCollectionID_Call) Return(n int64, err error) *MockCollectionItemRepository_SoftDeleteByCollectionID_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockCollectionItemRepository_SoftDeleteByCollectionID_Call) RunAndReturn(run func(ctx context.Context, exec bun.IDB, collectionID uuid.UUID) (int64, error)) *MockCollectionItemRepository_SoftDeleteByCollectionID_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDeleteByCollectionIDs provides a mock function for the type MockCollectionItemRepository
func (_mock *MockCollectionItemRepository) SoftDeleteByCollectionIDs(ctx context.Context, exec bun.IDB, collectionIDs []uuid.UUID) (int64, error) {
	ret := _mock.Called(ctx, exec, collectionIDs)

	if len(ret) == 0 {
		panic("no return value specified for SoftDeleteByCollectionIDs")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bun.IDB, []uuid.UUID) (int64, error)); ok {
		return returnFunc(ctx, exec, collectionIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bun.IDB, []uuid.UUID) int64); ok {
		r0 = returnFunc(ctx, exec, collectionIDs)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bun.IDB, []uuid.UUID) error); ok {
		r1 = returnFunc(ctx, exec, collectionIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCollectionItemRepository_SoftDeleteByCollectionIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDeleteByCollectionIDs'
type MockCollectionItemRepository_SoftDeleteByCollectionIDs_Call struct {
	*mock.Call
}

// SoftDeleteByCollectionIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - exec bun.IDB
//   - collectionIDs []uuid.UUID
func (_e *MockCollectionItemRepository_Expecter) SoftDeleteByCollectionIDs(ctx interface{}, exec interface{}, collectionIDs interface{}) *MockCollectionItemRepository_SoftDeleteByCollectionIDs_Call {
	return &MockCollectionItemRepository_SoftDeleteByCollectionIDs_Call{Call: _e.mock.On("SoftDeleteByCollectionIDs", ctx, exec, collectionIDs)}
}

func (_c *MockCollectionItemRepository_SoftDeleteByCollectionIDs_Call) Run(run func(ctx context.Context, exec bun.IDB, collectionIDs []uuid.UUID)) *MockCollectionItemRepository_SoftDeleteByCollectionIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bun.IDB
		if args[1] != nil {
			arg1 = args[1].(bun.IDB)
		}
		var arg2 []uuid.UUID
		if args[2] != nil {
			arg2 = args[2].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCollectionItemRepository_SoftDeleteByCollectionIDs_Call) Return(n int64, err error) *MockCollectionItemRepository_SoftDeleteByCollectionIDs_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockCollectionItemRepository_SoftDeleteByCollectionIDs_Call) RunAndReturn(run func(ctx context.Context, exec bun.IDB, collectionIDs []uuid.UUID) (int64, error)) *MockCollectionItemRepository_SoftDeleteByCollectionIDs_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockCollectionItemRepository
func (_mock *MockCollectionItemRepository) Update(ctx context.Context, item *entity.CollectionItem) (*entity.CollectionItem, error) {
	ret := _mock.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *entity.CollectionItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.CollectionItem) (*entity.CollectionItem, error)); ok {
		return returnFunc(ctx, item)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.CollectionItem) *entity.CollectionItem); ok {
		r0 = returnFunc(ctx, item)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.CollectionItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.CollectionItem) error); ok {
		r1 = returnFunc(ctx, item)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCollectionItemRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCollectionItemRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - item *entity.CollectionItem
func (_e *MockCollectionItemRepository_Expecter) Update(ctx interface{}, item interface{}) *MockCollectionItemRepository_Update_Call {
	return &MockCollectionItemRepository_Update_Call{Call: _e.mock.On("Update", ctx, item)}
}

func (_c *MockCollectionItemRepository_Update_Call) Run(run func(ctx context.Context, item *entity.CollectionItem)) *MockCollectionItemRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.CollectionItem
		if args[1] != nil {
			arg1 = args[1].(*entity.CollectionItem)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCollectionItemRepository_Update_Call) Return(collectionItem *entity.CollectionItem, err error) *MockCollectionItemRepository_Update_Call {
	_c.Call.Return(collectionItem, err)
	return _c
}

func (_c *MockCollectionItemRepository_Update_Call) RunAndReturn(run func(ctx context.Context, item *entity.CollectionItem) (*entity.CollectionItem, error)) *MockCollectionItemRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
