// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"backend/service-platform/app/internal/collection/entities"
	"backend/service-platform/app/internal/collection/repositories"
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"github.com/uptrace/bun"
)

// NewMockCollectionRepository creates a new instance of MockCollectionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCollectionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCollectionRepository {
	mock := &MockCollectionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCollectionRepository is an autogenerated mock type for the CollectionRepository type
type MockCollectionRepository struct {
	mock.Mock
}

type MockCollectionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCollectionRepository) EXPECT() *MockCollectionRepository_Expecter {
	return &MockCollectionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockCollectionRepository
func (_mock *MockCollectionRepository) Create(ctx context.Context, collection *entity.Collection) (*entity.Collection, error) {
	ret := _mock.Called(ctx, collection)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.Collection
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Collection) (*entity.Collection, error)); ok {
		return returnFunc(ctx, collection)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Collection) *entity.Collection); ok {
		r0 = returnFunc(ctx, collection)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Collection)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.Collection) error); ok {
		r1 = returnFunc(ctx, collection)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCollectionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCollectionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - collection *entity.Collection
func (_e *MockCollectionRepository_Expecter) Create(ctx interface{}, collection interface{}) *MockCollectionRepository_Create_Call {
	return &MockCollectionRepository_Create_Call{Call: _e.mock.On("Create", ctx, collection)}
}

func (_c *MockCollectionRepository_Create_Call) Run(run func(ctx context.Context, collection *entity.Collection)) *MockCollectionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Collection
		if args[1] != nil {
			arg1 = args[1].(*entity.Collection)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCollectionRepository_Create_Call) Return(collection1 *entity.Collection, err error) *MockCollectionRepository_Create_Call {
	_c.Call.Return(collection1, err)
	return _c
}

func (_c *MockCollectionRepository_Create_Call) RunAndReturn(run func(ctx context.Context, collection *entity.Collection) (*entity.Collection, error)) *MockCollectionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockCollectionRepository
func (_mock *MockCollectionRepository) FindByID(ctx context.Context, id uuid.UUID) (*entity.Collection, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.Collection
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Collection, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Collection); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Collection)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCollectionRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockCollectionRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockCollectionRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockCollectionRepository_FindByID_Call {
	return &MockCollectionRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockCollectionRepository_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockCollectionRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCollectionRepository_FindByID_Call) Return(collection *entity.Collection, err error) *MockCollectionRepository_FindByID_Call {
	_c.Call.Return(collection, err)
	return _c
}

func (_c *MockCollectionRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*entity.Collection, error)) *MockCollectionRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindBySlug provides a mock function for the type MockCollectionRepository
func (_mock *MockCollectionRepository) FindBySlug(ctx context.Context, slug string) (*entity.Collection, error) {
	ret := _mock.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for FindBySlug")
	}

	var r0 *entity.Collection
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.Collection, error)); ok {
		return returnFunc(ctx, slug)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.Collection); ok {
		r0 = returnFunc(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Collection)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCollectionRepository_FindBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBySlug'
type MockCollectionRepository_FindBySlug_Call struct {
	*mock.Call
}

// FindBySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *MockCollectionRepository_Expecter) FindBySlug(ctx interface{}, slug interface{}) *MockCollectionRepository_FindBySlug_Call {
	return &MockCollectionRepository_FindBySlug_Call{Call: _e.mock.On("FindBySlug", ctx, slug)}
}

func (_c *MockCollectionRepository_FindBySlug_Call) Run(run func(ctx context.Context, slug string)) *MockCollectionRepository_FindBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCollectionRepository_FindBySlug_Call) Return(collection *entity.Collection, err error) *MockCollectionRepository_FindBySlug_Call {
	_c.Call.Return(collection, err)
	return _c
}

func (_c *MockCollectionRepository_FindBySlug_Call) RunAndReturn(run func(ctx context.Context, slug string) (*entity.Collection, error)) *MockCollectionRepository_FindBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockCollectionRepository
func (_mock *MockCollectionRepository) List(ctx context.Context, filter repository.CollectionFilter) ([]entity.Collection, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []entity.Collection
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.CollectionFilter) ([]entity.Collection, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.CollectionFilter) []entity.Collection); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Collection)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repository.CollectionFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCollectionRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockCollectionRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter repository.CollectionFilter
func (_e *MockCollectionRepository_Expecter) List(ctx interface{}, filter interface{}) *MockCollectionRepository_List_Call {
	return &MockCollectionRepository_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *MockCollectionRepository_List_Call) Run(run func(ctx context.Context, filter repository.CollectionFilter)) *MockCollectionRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.CollectionFilter
		if args[1] != nil {
			arg1 = args[1].(repository.CollectionFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCollectionRepository_List_Call) Return(collections []entity.Collection, err error) *MockCollectionRepository_List_Call {
	_c.Call.Return(collections, err)
	return _c
}

func (_c *MockCollectionRepository_List_Call) RunAndReturn(run func(ctx context.Context, filter repository.CollectionFilter) ([]entity.Collection, error)) *MockCollectionRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDelete provides a mock function for the type MockCollectionRepository
func (_mock *MockCollectionRepository) SoftDelete(ctx context.Context, exec bun.IDB, id uuid.UUID) (int64, error) {
	ret := _mock.Called(ctx, exec, id)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bun.IDB, uuid.UUID) (int64, error)); ok {
		return returnFunc(ctx, exec, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bun.IDB, uuid.UUID) int64); ok {
		r0 = returnFunc(ctx, exec, id)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bun.IDB, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, exec, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCollectionRepository_SoftDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDelete'
type MockCollectionRepository_SoftDelete_Call struct {
	*mock.Call
}

// SoftDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - exec bun.IDB
//   - id uuid.UUID
func (_e *MockCollectionRepository_Expecter) SoftDelete(ctx interface{}, exec interface{}, id interface{}) *MockCollectionRepository_SoftDelete_Call {
	return &MockCollectionRepository_SoftDelete_Call{Call: _e.mock.On("SoftDelete", ctx, exec, id)}
}

func (_c *MockCollectionRepository_SoftDelete_Call) Run(run func(ctx context.Context, exec bun.IDB, id uuid.UUID)) *MockCollectionRepository_SoftDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bun.IDB
		if args[1] != nil {
			arg1 = args[1].(bun.IDB)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCollectionRepository_SoftDelete_Call) Return(n int64, err error) *MockCollectionRepository_SoftDelete_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockCollectionRepository_SoftDelete_Call) RunAndReturn(run func(ctx context.Context, exec bun.IDB, id uuid.UUID) (int64, error)) *MockCollectionRepository_SoftDelete_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockCollectionRepository
func (_mock *MockCollectionRepository) Update(ctx context.Context, collection *entity.Collection) (*entity.Collection, error) {
	ret := _mock.Called(ctx, collection)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *entity.Collection
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Collection) (*entity.Collection, error)); ok {
		return returnFunc(ctx, collection)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Collection) *entity.Collection); ok {
		r0 = returnFunc(ctx, collection)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Collection)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.Collection) error); ok {
		r1 = returnFunc(ctx, collection)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCollectionRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCollectionRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - collection *entity.Collection
func (_e *MockCollectionRepository_Expecter) Update(ctx interface{}, collection interface{}) *MockCollectionRepository_Update_Call {
	return &MockCollectionRepository_Update_Call{Call: _e.mock.On("Update", ctx, collection)}
}

func (_c *MockCollectionRepository_Update_Call) Run(run func(ctx context.Context, collection *entity.Collection)) *MockCollectionRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Collection
		if args[1] != nil {
			arg1 = args[1].(*entity.Collection)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCollectionRepository_Update_Call) Return(collection1 *entity.Collection, err error) *MockCollectionRepository_Update_Call {
	_c.Call.Return(collection1, err)
	return _c
}

func (_c *MockCollectionRepository_Update_Call) RunAndReturn(run func(ctx context.Context, collection *entity.Collection) (*entity.Collection, error)) *MockCollectionRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
