// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"backend/service-platform/app/internal/collection/entities"
	"backend/service-platform/app/internal/collection/repositories"
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRarityConfigRepository creates a new instance of MockRarityConfigRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRarityConfigRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRarityConfigRepository {
	mock := &MockRarityConfigRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRarityConfigRepository is an autogenerated mock type for the RarityConfigRepository type
type MockRarityConfigRepository struct {
	mock.Mock
}

type MockRarityConfigRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRarityConfigRepository) EXPECT() *MockRarityConfigRepository_Expecter {
	return &MockRarityConfigRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockRarityConfigRepository
func (_mock *MockRarityConfigRepository) Create(ctx context.Context, rc *entity.RarityConfig) (*entity.RarityConfig, error) {
	ret := _mock.Called(ctx, rc)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.RarityConfig
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.RarityConfig) (*entity.RarityConfig, error)); ok {
		return returnFunc(ctx, rc)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.RarityConfig) *entity.RarityConfig); ok {
		r0 = returnFunc(ctx, rc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.RarityConfig)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.RarityConfig) error); ok {
		r1 = returnFunc(ctx, rc)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRarityConfigRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRarityConfigRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - rc *entity.RarityConfig
func (_e *MockRarityConfigRepository_Expecter) Create(ctx interface{}, rc interface{}) *MockRarityConfigRepository_Create_Call {
	return &MockRarityConfigRepository_Create_Call{Call: _e.mock.On("Create", ctx, rc)}
}

func (_c *MockRarityConfigRepository_Create_Call) Run(run func(ctx context.Context, rc *entity.RarityConfig)) *MockRarityConfigRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.RarityConfig
		if args[1] != nil {
			arg1 = args[1].(*entity.RarityConfig)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRarityConfigRepository_Create_Call) Return(rarityConfig *entity.RarityConfig, err error) *MockRarityConfigRepository_Create_Call {
	_c.Call.Return(rarityConfig, err)
	return _c
}

func (_c *MockRarityConfigRepository_Create_Call) RunAndReturn(run func(ctx context.Context, rc *entity.RarityConfig) (*entity.RarityConfig, error)) *MockRarityConfigRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByCode provides a mock function for the type MockRarityConfigRepository
func (_mock *MockRarityConfigRepository) FindByCode(ctx context.Context, code string) (*entity.RarityConfig, error) {
	ret := _mock.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for FindByCode")
	}

	var r0 *entity.RarityConfig
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.RarityConfig, error)); ok {
		return returnFunc(ctx, code)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.RarityConfig); ok {
		r0 = returnFunc(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.RarityConfig)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, code)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRarityConfigRepository_FindByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByCode'
type MockRarityConfigRepository_FindByCode_Call struct {
	*mock.Call
}

// FindByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *MockRarityConfigRepository_Expecter) FindByCode(ctx interface{}, code interface{}) *MockRarityConfigRepository_FindByCode_Call {
	return &MockRarityConfigRepository_FindByCode_Call{Call: _e.mock.On("FindByCode", ctx, code)}
}

func (_c *MockRarityConfigRepository_FindByCode_Call) Run(run func(ctx context.Context, code string)) *MockRarityConfigRepository_FindByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRarityConfigRepository_FindByCode_Call) Return(rarityConfig *entity.RarityConfig, err error) *MockRarityConfigRepository_FindByCode_Call {
	_c.Call.Return(rarityConfig, err)
	return _c
}

func (_c *MockRarityConfigRepository_FindByCode_Call) RunAndReturn(run func(ctx context.Context, code string) (*entity.RarityConfig, error)) *MockRarityConfigRepository_FindByCode_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockRarityConfigRepository
func (_mock *MockRarityConfigRepository) FindByID(ctx context.Context, id uuid.UUID) (*entity.RarityConfig, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.RarityConfig
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.RarityConfig, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.RarityConfig); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.RarityConfig)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRarityConfigRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockRarityConfigRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRarityConfigRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockRarityConfigRepository_FindByID_Call {
	return &MockRarityConfigRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockRarityConfigRepository_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRarityConfigRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRarityConfigRepository_FindByID_Call) Return(rarityConfig *entity.RarityConfig, err error) *MockRarityConfigRepository_FindByID_Call {
	_c.Call.Return(rarityConfig, err)
	return _c
}

func (_c *MockRarityConfigRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*entity.RarityConfig, error)) *MockRarityConfigRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockRarityConfigRepository
func (_mock *MockRarityConfigRepository) List(ctx context.Context, filter repository.RarityConfigFilter) ([]entity.RarityConfig, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []entity.RarityConfig
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.RarityConfigFilter) ([]entity.RarityConfig, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.RarityConfigFilter) []entity.RarityConfig); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.RarityConfig)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repository.RarityConfigFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRarityConfigRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRarityConfigRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter repository.RarityConfigFilter
func (_e *MockRarityConfigRepository_Expecter) List(ctx interface{}, filter interface{}) *MockRarityConfigRepository_List_Call {
	return &MockRarityConfigRepository_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *MockRarityConfigRepository_List_Call) Run(run func(ctx context.Context, filter repository.RarityConfigFilter)) *MockRarityConfigRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.RarityConfigFilter
		if args[1] != nil {
			arg1 = args[1].(repository.RarityConfigFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRarityConfigRepository_List_Call) Return(rarityConfigs []entity.RarityConfig, err error) *MockRarityConfigRepository_List_Call {
	_c.Call.Return(rarityConfigs, err)
	return _c
}

func (_c *MockRarityConfigRepository_List_Call) RunAndReturn(run func(ctx context.Context, filter repository.RarityConfigFilter) ([]entity.RarityConfig, error)) *MockRarityConfigRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockRarityConfigRepository
func (_mock *MockRarityConfigRepository) Update(ctx context.Context, rc *entity.RarityConfig) (*entity.RarityConfig, error) {
	ret := _mock.Called(ctx, rc)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *entity.RarityConfig
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.RarityConfig) (*entity.RarityConfig, error)); ok {
		return returnFunc(ctx, rc)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.RarityConfig) *entity.RarityConfig); ok {
		r0 = returnFunc(ctx, rc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.RarityConfig)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.RarityConfig) error); ok {
		r1 = returnFunc(ctx, rc)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRarityConfigRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRarityConfigRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - rc *entity.RarityConfig
func (_e *MockRarityConfigRepository_Expecter) Update(ctx interface{}, rc interface{}) *MockRarityConfigRepository_Update_Call {
	return &MockRarityConfigRepository_Update_Call{Call: _e.mock.On("Update", ctx, rc)}
}

func (_c *MockRarityConfigRepository_Update_Call) Run(run func(ctx context.Context, rc *entity.RarityConfig)) *MockRarityConfigRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.RarityConfig
		if args[1] != nil {
			arg1 = args[1].(*entity.RarityConfig)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRarityConfigRepository_Update_Call) Return(rarityConfig *entity.RarityConfig, err error) *MockRarityConfigRepository_Update_Call {
	_c.Call.Return(rarityConfig, err)
	return _c
}

func (_c *MockRarityConfigRepository_Update_Call) RunAndReturn(run func(ctx context.Context, rc *entity.RarityConfig) (*entity.RarityConfig, error)) *MockRarityConfigRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
