// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"backend/service-platform/app/internal/user/constants/currency"
	"backend/service-platform/app/internal/user/constants/transaction"
	"backend/service-platform/app/internal/user/entities"
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserBalanceTransactionRepository creates a new instance of MockUserBalanceTransactionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserBalanceTransactionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserBalanceTransactionRepository {
	mock := &MockUserBalanceTransactionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserBalanceTransactionRepository is an autogenerated mock type for the UserBalanceTransactionRepository type
type MockUserBalanceTransactionRepository struct {
	mock.Mock
}

type MockUserBalanceTransactionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserBalanceTransactionRepository) EXPECT() *MockUserBalanceTransactionRepository_Expecter {
	return &MockUserBalanceTransactionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockUserBalanceTransactionRepository
func (_mock *MockUserBalanceTransactionRepository) Create(ctx context.Context, tx *entity.UserBalanceTransaction) (*entity.UserBalanceTransaction, error) {
	ret := _mock.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.UserBalanceTransaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.UserBalanceTransaction) (*entity.UserBalanceTransaction, error)); ok {
		return returnFunc(ctx, tx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.UserBalanceTransaction) *entity.UserBalanceTransaction); ok {
		r0 = returnFunc(ctx, tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.UserBalanceTransaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.UserBalanceTransaction) error); ok {
		r1 = returnFunc(ctx, tx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserBalanceTransactionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserBalanceTransactionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *entity.UserBalanceTransaction
func (_e *MockUserBalanceTransactionRepository_Expecter) Create(ctx interface{}, tx interface{}) *MockUserBalanceTransactionRepository_Create_Call {
	return &MockUserBalanceTransactionRepository_Create_Call{Call: _e.mock.On("Create", ctx, tx)}
}

func (_c *MockUserBalanceTransactionRepository_Create_Call) Run(run func(ctx context.Context, tx *entity.UserBalanceTransaction)) *MockUserBalanceTransactionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.UserBalanceTransaction
		if args[1] != nil {
			arg1 = args[1].(*entity.UserBalanceTransaction)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserBalanceTransactionRepository_Create_Call) Return(userBalanceTransaction *entity.UserBalanceTransaction, err error) *MockUserBalanceTransactionRepository_Create_Call {
	_c.Call.Return(userBalanceTransaction, err)
	return _c
}

func (_c *MockUserBalanceTransactionRepository_Create_Call) RunAndReturn(run func(ctx context.Context, tx *entity.UserBalanceTransaction) (*entity.UserBalanceTransaction, error)) *MockUserBalanceTransactionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function for the type MockUserBalanceTransactionRepository
func (_mock *MockUserBalanceTransactionRepository) ListByUser(ctx context.Context, userID uuid.UUID, _currency *currency.Currency, _type *transaction.TransactionType) ([]entity.UserBalanceTransaction, error) {
	ret := _mock.Called(ctx, userID, _currency, _type)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []entity.UserBalanceTransaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *currency.Currency, *transaction.TransactionType) ([]entity.UserBalanceTransaction, error)); ok {
		return returnFunc(ctx, userID, _currency, _type)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *currency.Currency, *transaction.TransactionType) []entity.UserBalanceTransaction); ok {
		r0 = returnFunc(ctx, userID, _currency, _type)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.UserBalanceTransaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, *currency.Currency, *transaction.TransactionType) error); ok {
		r1 = returnFunc(ctx, userID, _currency, _type)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserBalanceTransactionRepository_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type MockUserBalanceTransactionRepository_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - _currency *currency.Currency
//   - _type *transaction.TransactionType
func (_e *MockUserBalanceTransactionRepository_Expecter) ListByUser(ctx interface{}, userID interface{}, _currency interface{}, _type interface{}) *MockUserBalanceTransactionRepository_ListByUser_Call {
	return &MockUserBalanceTransactionRepository_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, userID, _currency, _type)}
}

func (_c *MockUserBalanceTransactionRepository_ListByUser_Call) Run(run func(ctx context.Context, userID uuid.UUID, _currency *currency.Currency, _type *transaction.TransactionType)) *MockUserBalanceTransactionRepository_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *currency.Currency
		if args[2] != nil {
			arg2 = args[2].(*currency.Currency)
		}
		var arg3 *transaction.TransactionType
		if args[3] != nil {
			arg3 = args[3].(*transaction.TransactionType)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUserBalanceTransactionRepository_ListByUser_Call) Return(userBalanceTransactions []entity.UserBalanceTransaction, err error) *MockUserBalanceTransactionRepository_ListByUser_Call {
	_c.Call.Return(userBalanceTransactions, err)
	return _c
}

func (_c *MockUserBalanceTransactionRepository_ListByUser_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, _currency *currency.Currency, _type *transaction.TransactionType) ([]entity.UserBalanceTransaction, error)) *MockUserBalanceTransactionRepository_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}
