// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"backend/service-platform/app/internal/user/constants/currency"
	"backend/service-platform/app/internal/user/entities"
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserBalanceRepository creates a new instance of MockUserBalanceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserBalanceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserBalanceRepository {
	mock := &MockUserBalanceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserBalanceRepository is an autogenerated mock type for the UserBalanceRepository type
type MockUserBalanceRepository struct {
	mock.Mock
}

type MockUserBalanceRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserBalanceRepository) EXPECT() *MockUserBalanceRepository_Expecter {
	return &MockUserBalanceRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockUserBalanceRepository
func (_mock *MockUserBalanceRepository) Create(ctx context.Context, balance *entity.UserBalance) (*entity.UserBalance, error) {
	ret := _mock.Called(ctx, balance)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.UserBalance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.UserBalance) (*entity.UserBalance, error)); ok {
		return returnFunc(ctx, balance)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.UserBalance) *entity.UserBalance); ok {
		r0 = returnFunc(ctx, balance)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.UserBalance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.UserBalance) error); ok {
		r1 = returnFunc(ctx, balance)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserBalanceRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserBalanceRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - balance *entity.UserBalance
func (_e *MockUserBalanceRepository_Expecter) Create(ctx interface{}, balance interface{}) *MockUserBalanceRepository_Create_Call {
	return &MockUserBalanceRepository_Create_Call{Call: _e.mock.On("Create", ctx, balance)}
}

func (_c *MockUserBalanceRepository_Create_Call) Run(run func(ctx context.Context, balance *entity.UserBalance)) *MockUserBalanceRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.UserBalance
		if args[1] != nil {
			arg1 = args[1].(*entity.UserBalance)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserBalanceRepository_Create_Call) Return(userBalance *entity.UserBalance, err error) *MockUserBalanceRepository_Create_Call {
	_c.Call.Return(userBalance, err)
	return _c
}

func (_c *MockUserBalanceRepository_Create_Call) RunAndReturn(run func(ctx context.Context, balance *entity.UserBalance) (*entity.UserBalance, error)) *MockUserBalanceRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAllByUserID provides a mock function for the type MockUserBalanceRepository
func (_mock *MockUserBalanceRepository) DeleteAllByUserID(ctx context.Context, userID uuid.UUID) (int64, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAllByUserID")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int64, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) int64); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserBalanceRepository_DeleteAllByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAllByUserID'
type MockUserBalanceRepository_DeleteAllByUserID_Call struct {
	*mock.Call
}

// DeleteAllByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockUserBalanceRepository_Expecter) DeleteAllByUserID(ctx interface{}, userID interface{}) *MockUserBalanceRepository_DeleteAllByUserID_Call {
	return &MockUserBalanceRepository_DeleteAllByUserID_Call{Call: _e.mock.On("DeleteAllByUserID", ctx, userID)}
}

func (_c *MockUserBalanceRepository_DeleteAllByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockUserBalanceRepository_DeleteAllByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserBalanceRepository_DeleteAllByUserID_Call) Return(n int64, err error) *MockUserBalanceRepository_DeleteAllByUserID_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockUserBalanceRepository_DeleteAllByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (int64, error)) *MockUserBalanceRepository_DeleteAllByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllByUserID provides a mock function for the type MockUserBalanceRepository
func (_mock *MockUserBalanceRepository) FindAllByUserID(ctx context.Context, userID uuid.UUID) ([]entity.UserBalance, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByUserID")
	}

	var r0 []entity.UserBalance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]entity.UserBalance, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []entity.UserBalance); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.UserBalance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserBalanceRepository_FindAllByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllByUserID'
type MockUserBalanceRepository_FindAllByUserID_Call struct {
	*mock.Call
}

// FindAllByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockUserBalanceRepository_Expecter) FindAllByUserID(ctx interface{}, userID interface{}) *MockUserBalanceRepository_FindAllByUserID_Call {
	return &MockUserBalanceRepository_FindAllByUserID_Call{Call: _e.mock.On("FindAllByUserID", ctx, userID)}
}

func (_c *MockUserBalanceRepository_FindAllByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockUserBalanceRepository_FindAllByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserBalanceRepository_FindAllByUserID_Call) Return(userBalances []entity.UserBalance, err error) *MockUserBalanceRepository_FindAllByUserID_Call {
	_c.Call.Return(userBalances, err)
	return _c
}

func (_c *MockUserBalanceRepository_FindAllByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) ([]entity.UserBalance, error)) *MockUserBalanceRepository_FindAllByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserAndCurrency provides a mock function for the type MockUserBalanceRepository
func (_mock *MockUserBalanceRepository) FindByUserAndCurrency(ctx context.Context, userID uuid.UUID, currency1 currency.Currency) (*entity.UserBalance, error) {
	ret := _mock.Called(ctx, userID, currency1)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserAndCurrency")
	}

	var r0 *entity.UserBalance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, currency.Currency) (*entity.UserBalance, error)); ok {
		return returnFunc(ctx, userID, currency1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, currency.Currency) *entity.UserBalance); ok {
		r0 = returnFunc(ctx, userID, currency1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.UserBalance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, currency.Currency) error); ok {
		r1 = returnFunc(ctx, userID, currency1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserBalanceRepository_FindByUserAndCurrency_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserAndCurrency'
type MockUserBalanceRepository_FindByUserAndCurrency_Call struct {
	*mock.Call
}

// FindByUserAndCurrency is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - currency1 currency.Currency
func (_e *MockUserBalanceRepository_Expecter) FindByUserAndCurrency(ctx interface{}, userID interface{}, currency1 interface{}) *MockUserBalanceRepository_FindByUserAndCurrency_Call {
	return &MockUserBalanceRepository_FindByUserAndCurrency_Call{Call: _e.mock.On("FindByUserAndCurrency", ctx, userID, currency1)}
}

func (_c *MockUserBalanceRepository_FindByUserAndCurrency_Call) Run(run func(ctx context.Context, userID uuid.UUID, currency1 currency.Currency)) *MockUserBalanceRepository_FindByUserAndCurrency_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 currency.Currency
		if args[2] != nil {
			arg2 = args[2].(currency.Currency)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserBalanceRepository_FindByUserAndCurrency_Call) Return(userBalance *entity.UserBalance, err error) *MockUserBalanceRepository_FindByUserAndCurrency_Call {
	_c.Call.Return(userBalance, err)
	return _c
}

func (_c *MockUserBalanceRepository_FindByUserAndCurrency_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, currency1 currency.Currency) (*entity.UserBalance, error)) *MockUserBalanceRepository_FindByUserAndCurrency_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertAndAddDelta provides a mock function for the type MockUserBalanceRepository
func (_mock *MockUserBalanceRepository) UpsertAndAddDelta(ctx context.Context, userID uuid.UUID, currency1 currency.Currency, delta int64) (*entity.UserBalance, int64, error) {
	ret := _mock.Called(ctx, userID, currency1, delta)

	if len(ret) == 0 {
		panic("no return value specified for UpsertAndAddDelta")
	}

	var r0 *entity.UserBalance
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, currency.Currency, int64) (*entity.UserBalance, int64, error)); ok {
		return returnFunc(ctx, userID, currency1, delta)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, currency.Currency, int64) *entity.UserBalance); ok {
		r0 = returnFunc(ctx, userID, currency1, delta)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.UserBalance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, currency.Currency, int64) int64); ok {
		r1 = returnFunc(ctx, userID, currency1, delta)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID, currency.Currency, int64) error); ok {
		r2 = returnFunc(ctx, userID, currency1, delta)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockUserBalanceRepository_UpsertAndAddDelta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertAndAddDelta'
type MockUserBalanceRepository_UpsertAndAddDelta_Call struct {
	*mock.Call
}

// UpsertAndAddDelta is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - currency1 currency.Currency
//   - delta int64
func (_e *MockUserBalanceRepository_Expecter) UpsertAndAddDelta(ctx interface{}, userID interface{}, currency1 interface{}, delta interface{}) *MockUserBalanceRepository_UpsertAndAddDelta_Call {
	return &MockUserBalanceRepository_UpsertAndAddDelta_Call{Call: _e.mock.On("UpsertAndAddDelta", ctx, userID, currency1, delta)}
}

func (_c *MockUserBalanceRepository_UpsertAndAddDelta_Call) Run(run func(ctx context.Context, userID uuid.UUID, currency1 currency.Currency, delta int64)) *MockUserBalanceRepository_UpsertAndAddDelta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 currency.Currency
		if args[2] != nil {
			arg2 = args[2].(currency.Currency)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUserBalanceRepository_UpsertAndAddDelta_Call) Return(userBalance *entity.UserBalance, n int64, err error) *MockUserBalanceRepository_UpsertAndAddDelta_Call {
	_c.Call.Return(userBalance, n, err)
	return _c
}

func (_c *MockUserBalanceRepository_UpsertAndAddDelta_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, currency1 currency.Currency, delta int64) (*entity.UserBalance, int64, error)) *MockUserBalanceRepository_UpsertAndAddDelta_Call {
	_c.Call.Return(run)
	return _c
}
