// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/go-playground/validator/v10"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIValidator creates a new instance of MockIValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIValidator {
	mock := &MockIValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIValidator is an autogenerated mock type for the IValidator type
type MockIValidator struct {
	mock.Mock
}

type MockIValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIValidator) EXPECT() *MockIValidator_Expecter {
	return &MockIValidator_Expecter{mock: &_m.Mock}
}

// Register provides a mock function for the type MockIValidator
func (_mock *MockIValidator) Register() (validator.Func, string) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 validator.Func
	var r1 string
	if returnFunc, ok := ret.Get(0).(func() (validator.Func, string)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() validator.Func); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(validator.Func)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() string); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(string)
	}
	return r0, r1
}

// MockIValidator_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockIValidator_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
func (_e *MockIValidator_Expecter) Register() *MockIValidator_Register_Call {
	return &MockIValidator_Register_Call{Call: _e.mock.On("Register")}
}

func (_c *MockIValidator_Register_Call) Run(run func()) *MockIValidator_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIValidator_Register_Call) Return(funcParam validator.Func, s string) *MockIValidator_Register_Call {
	_c.Call.Return(funcParam, s)
	return _c
}

func (_c *MockIValidator_Register_Call) RunAndReturn(run func() (validator.Func, string)) *MockIValidator_Register_Call {
	_c.Call.Return(run)
	return _c
}
