// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockDBTable creates a new instance of MockDBTable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDBTable(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDBTable {
	mock := &MockDBTable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDBTable is an autogenerated mock type for the DBTable type
type MockDBTable struct {
	mock.Mock
}

type MockDBTable_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDBTable) EXPECT() *MockDBTable_Expecter {
	return &MockDBTable_Expecter{mock: &_m.Mock}
}

// Alias provides a mock function for the type MockDBTable
func (_mock *MockDBTable) Alias() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Alias")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockDBTable_Alias_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Alias'
type MockDBTable_Alias_Call struct {
	*mock.Call
}

// Alias is a helper method to define mock.On call
func (_e *MockDBTable_Expecter) Alias() *MockDBTable_Alias_Call {
	return &MockDBTable_Alias_Call{Call: _e.mock.On("Alias")}
}

func (_c *MockDBTable_Alias_Call) Run(run func()) *MockDBTable_Alias_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDBTable_Alias_Call) Return(s string) *MockDBTable_Alias_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockDBTable_Alias_Call) RunAndReturn(run func() string) *MockDBTable_Alias_Call {
	_c.Call.Return(run)
	return _c
}
