// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"backend/service-platform/app/internal/platform/middleware"

	"github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthentication creates a new instance of MockAuthentication. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthentication(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthentication {
	mock := &MockAuthentication{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthentication is an autogenerated mock type for the Authentication type
type MockAuthentication struct {
	mock.Mock
}

type MockAuthentication_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthentication) EXPECT() *MockAuthentication_Expecter {
	return &MockAuthentication_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function for the type MockAuthentication
func (_mock *MockAuthentication) Authenticate(ec echo.Context) (*middleware.AuthenticationResult, error) {
	ret := _mock.Called(ec)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 *middleware.AuthenticationResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(echo.Context) (*middleware.AuthenticationResult, error)); ok {
		return returnFunc(ec)
	}
	if returnFunc, ok := ret.Get(0).(func(echo.Context) *middleware.AuthenticationResult); ok {
		r0 = returnFunc(ec)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*middleware.AuthenticationResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(echo.Context) error); ok {
		r1 = returnFunc(ec)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthentication_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type MockAuthentication_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - ec echo.Context
func (_e *MockAuthentication_Expecter) Authenticate(ec interface{}) *MockAuthentication_Authenticate_Call {
	return &MockAuthentication_Authenticate_Call{Call: _e.mock.On("Authenticate", ec)}
}

func (_c *MockAuthentication_Authenticate_Call) Run(run func(ec echo.Context)) *MockAuthentication_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 echo.Context
		if args[0] != nil {
			arg0 = args[0].(echo.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthentication_Authenticate_Call) Return(authenticationResult *middleware.AuthenticationResult, err error) *MockAuthentication_Authenticate_Call {
	_c.Call.Return(authenticationResult, err)
	return _c
}

func (_c *MockAuthentication_Authenticate_Call) RunAndReturn(run func(ec echo.Context) (*middleware.AuthenticationResult, error)) *MockAuthentication_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// CanHandle provides a mock function for the type MockAuthentication
func (_mock *MockAuthentication) CanHandle(ec echo.Context) bool {
	ret := _mock.Called(ec)

	if len(ret) == 0 {
		panic("no return value specified for CanHandle")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(echo.Context) bool); ok {
		r0 = returnFunc(ec)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockAuthentication_CanHandle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanHandle'
type MockAuthentication_CanHandle_Call struct {
	*mock.Call
}

// CanHandle is a helper method to define mock.On call
//   - ec echo.Context
func (_e *MockAuthentication_Expecter) CanHandle(ec interface{}) *MockAuthentication_CanHandle_Call {
	return &MockAuthentication_CanHandle_Call{Call: _e.mock.On("CanHandle", ec)}
}

func (_c *MockAuthentication_CanHandle_Call) Run(run func(ec echo.Context)) *MockAuthentication_CanHandle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 echo.Context
		if args[0] != nil {
			arg0 = args[0].(echo.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthentication_CanHandle_Call) Return(b bool) *MockAuthentication_CanHandle_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockAuthentication_CanHandle_Call) RunAndReturn(run func(ec echo.Context) bool) *MockAuthentication_CanHandle_Call {
	_c.Call.Return(run)
	return _c
}

// CreateErrorResponse provides a mock function for the type MockAuthentication
func (_mock *MockAuthentication) CreateErrorResponse(statusCode int, message string) *echo.HTTPError {
	ret := _mock.Called(statusCode, message)

	if len(ret) == 0 {
		panic("no return value specified for CreateErrorResponse")
	}

	var r0 *echo.HTTPError
	if returnFunc, ok := ret.Get(0).(func(int, string) *echo.HTTPError); ok {
		r0 = returnFunc(statusCode, message)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*echo.HTTPError)
		}
	}
	return r0
}

// MockAuthentication_CreateErrorResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateErrorResponse'
type MockAuthentication_CreateErrorResponse_Call struct {
	*mock.Call
}

// CreateErrorResponse is a helper method to define mock.On call
//   - statusCode int
//   - message string
func (_e *MockAuthentication_Expecter) CreateErrorResponse(statusCode interface{}, message interface{}) *MockAuthentication_CreateErrorResponse_Call {
	return &MockAuthentication_CreateErrorResponse_Call{Call: _e.mock.On("CreateErrorResponse", statusCode, message)}
}

func (_c *MockAuthentication_CreateErrorResponse_Call) Run(run func(statusCode int, message string)) *MockAuthentication_CreateErrorResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthentication_CreateErrorResponse_Call) Return(hTTPError *echo.HTTPError) *MockAuthentication_CreateErrorResponse_Call {
	_c.Call.Return(hTTPError)
	return _c
}

func (_c *MockAuthentication_CreateErrorResponse_Call) RunAndReturn(run func(statusCode int, message string) *echo.HTTPError) *MockAuthentication_CreateErrorResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetAuthenticationMethod provides a mock function for the type MockAuthentication
func (_mock *MockAuthentication) GetAuthenticationMethod(c echo.Context) (string, error) {
	ret := _mock.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthenticationMethod")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(echo.Context) (string, error)); ok {
		return returnFunc(c)
	}
	if returnFunc, ok := ret.Get(0).(func(echo.Context) string); ok {
		r0 = returnFunc(c)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(echo.Context) error); ok {
		r1 = returnFunc(c)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthentication_GetAuthenticationMethod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthenticationMethod'
type MockAuthentication_GetAuthenticationMethod_Call struct {
	*mock.Call
}

// GetAuthenticationMethod is a helper method to define mock.On call
//   - c echo.Context
func (_e *MockAuthentication_Expecter) GetAuthenticationMethod(c interface{}) *MockAuthentication_GetAuthenticationMethod_Call {
	return &MockAuthentication_GetAuthenticationMethod_Call{Call: _e.mock.On("GetAuthenticationMethod", c)}
}

func (_c *MockAuthentication_GetAuthenticationMethod_Call) Run(run func(c echo.Context)) *MockAuthentication_GetAuthenticationMethod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 echo.Context
		if args[0] != nil {
			arg0 = args[0].(echo.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthentication_GetAuthenticationMethod_Call) Return(s string, err error) *MockAuthentication_GetAuthenticationMethod_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockAuthentication_GetAuthenticationMethod_Call) RunAndReturn(run func(c echo.Context) (string, error)) *MockAuthentication_GetAuthenticationMethod_Call {
	_c.Call.Return(run)
	return _c
}

// GetName provides a mock function for the type MockAuthentication
func (_mock *MockAuthentication) GetName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockAuthentication_GetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetName'
type MockAuthentication_GetName_Call struct {
	*mock.Call
}

// GetName is a helper method to define mock.On call
func (_e *MockAuthentication_Expecter) GetName() *MockAuthentication_GetName_Call {
	return &MockAuthentication_GetName_Call{Call: _e.mock.On("GetName")}
}

func (_c *MockAuthentication_GetName_Call) Run(run func()) *MockAuthentication_GetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAuthentication_GetName_Call) Return(s string) *MockAuthentication_GetName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockAuthentication_GetName_Call) RunAndReturn(run func() string) *MockAuthentication_GetName_Call {
	_c.Call.Return(run)
	return _c
}

// HasRequiredRole provides a mock function for the type MockAuthentication
func (_mock *MockAuthentication) HasRequiredRole(userRole string, requiredRole string) bool {
	ret := _mock.Called(userRole, requiredRole)

	if len(ret) == 0 {
		panic("no return value specified for HasRequiredRole")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = returnFunc(userRole, requiredRole)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockAuthentication_HasRequiredRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasRequiredRole'
type MockAuthentication_HasRequiredRole_Call struct {
	*mock.Call
}

// HasRequiredRole is a helper method to define mock.On call
//   - userRole string
//   - requiredRole string
func (_e *MockAuthentication_Expecter) HasRequiredRole(userRole interface{}, requiredRole interface{}) *MockAuthentication_HasRequiredRole_Call {
	return &MockAuthentication_HasRequiredRole_Call{Call: _e.mock.On("HasRequiredRole", userRole, requiredRole)}
}

func (_c *MockAuthentication_HasRequiredRole_Call) Run(run func(userRole string, requiredRole string)) *MockAuthentication_HasRequiredRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthentication_HasRequiredRole_Call) Return(b bool) *MockAuthentication_HasRequiredRole_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockAuthentication_HasRequiredRole_Call) RunAndReturn(run func(userRole string, requiredRole string) bool) *MockAuthentication_HasRequiredRole_Call {
	_c.Call.Return(run)
	return _c
}

// RequireAuth provides a mock function for the type MockAuthentication
func (_mock *MockAuthentication) RequireAuth() echo.MiddlewareFunc {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RequireAuth")
	}

	var r0 echo.MiddlewareFunc
	if returnFunc, ok := ret.Get(0).(func() echo.MiddlewareFunc); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.MiddlewareFunc)
		}
	}
	return r0
}

// MockAuthentication_RequireAuth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequireAuth'
type MockAuthentication_RequireAuth_Call struct {
	*mock.Call
}

// RequireAuth is a helper method to define mock.On call
func (_e *MockAuthentication_Expecter) RequireAuth() *MockAuthentication_RequireAuth_Call {
	return &MockAuthentication_RequireAuth_Call{Call: _e.mock.On("RequireAuth")}
}

func (_c *MockAuthentication_RequireAuth_Call) Run(run func()) *MockAuthentication_RequireAuth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAuthentication_RequireAuth_Call) Return(middlewareFunc echo.MiddlewareFunc) *MockAuthentication_RequireAuth_Call {
	_c.Call.Return(middlewareFunc)
	return _c
}

func (_c *MockAuthentication_RequireAuth_Call) RunAndReturn(run func() echo.MiddlewareFunc) *MockAuthentication_RequireAuth_Call {
	_c.Call.Return(run)
	return _c
}

// RequireRole provides a mock function for the type MockAuthentication
func (_mock *MockAuthentication) RequireRole(requiredRole string) echo.MiddlewareFunc {
	ret := _mock.Called(requiredRole)

	if len(ret) == 0 {
		panic("no return value specified for RequireRole")
	}

	var r0 echo.MiddlewareFunc
	if returnFunc, ok := ret.Get(0).(func(string) echo.MiddlewareFunc); ok {
		r0 = returnFunc(requiredRole)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.MiddlewareFunc)
		}
	}
	return r0
}

// MockAuthentication_RequireRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequireRole'
type MockAuthentication_RequireRole_Call struct {
	*mock.Call
}

// RequireRole is a helper method to define mock.On call
//   - requiredRole string
func (_e *MockAuthentication_Expecter) RequireRole(requiredRole interface{}) *MockAuthentication_RequireRole_Call {
	return &MockAuthentication_RequireRole_Call{Call: _e.mock.On("RequireRole", requiredRole)}
}

func (_c *MockAuthentication_RequireRole_Call) Run(run func(requiredRole string)) *MockAuthentication_RequireRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthentication_RequireRole_Call) Return(middlewareFunc echo.MiddlewareFunc) *MockAuthentication_RequireRole_Call {
	_c.Call.Return(middlewareFunc)
	return _c
}

func (_c *MockAuthentication_RequireRole_Call) RunAndReturn(run func(requiredRole string) echo.MiddlewareFunc) *MockAuthentication_RequireRole_Call {
	_c.Call.Return(run)
	return _c
}

// SetUserContext provides a mock function for the type MockAuthentication
func (_mock *MockAuthentication) SetUserContext(c echo.Context, result *middleware.AuthenticationResult) {
	_mock.Called(c, result)
	return
}

// MockAuthentication_SetUserContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUserContext'
type MockAuthentication_SetUserContext_Call struct {
	*mock.Call
}

// SetUserContext is a helper method to define mock.On call
//   - c echo.Context
//   - result *middleware.AuthenticationResult
func (_e *MockAuthentication_Expecter) SetUserContext(c interface{}, result interface{}) *MockAuthentication_SetUserContext_Call {
	return &MockAuthentication_SetUserContext_Call{Call: _e.mock.On("SetUserContext", c, result)}
}

func (_c *MockAuthentication_SetUserContext_Call) Run(run func(c echo.Context, result *middleware.AuthenticationResult)) *MockAuthentication_SetUserContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 echo.Context
		if args[0] != nil {
			arg0 = args[0].(echo.Context)
		}
		var arg1 *middleware.AuthenticationResult
		if args[1] != nil {
			arg1 = args[1].(*middleware.AuthenticationResult)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthentication_SetUserContext_Call) Return() *MockAuthentication_SetUserContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAuthentication_SetUserContext_Call) RunAndReturn(run func(c echo.Context, result *middleware.AuthenticationResult)) *MockAuthentication_SetUserContext_Call {
	_c.Run(run)
	return _c
}
