// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"backend/service-platform/app/internal/job/constants"
	"backend/service-platform/app/internal/job/entities"
	"context"
	"time"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockJobRepository creates a new instance of MockJobRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJobRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJobRepository {
	mock := &MockJobRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJobRepository is an autogenerated mock type for the JobRepository type
type MockJobRepository struct {
	mock.Mock
}

type MockJobRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJobRepository) EXPECT() *MockJobRepository_Expecter {
	return &MockJobRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockJobRepository
func (_mock *MockJobRepository) Create(ctx context.Context, job *entity.Job) error {
	ret := _mock.Called(ctx, job)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Job) error); ok {
		r0 = returnFunc(ctx, job)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockJobRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockJobRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - job *entity.Job
func (_e *MockJobRepository_Expecter) Create(ctx interface{}, job interface{}) *MockJobRepository_Create_Call {
	return &MockJobRepository_Create_Call{Call: _e.mock.On("Create", ctx, job)}
}

func (_c *MockJobRepository_Create_Call) Run(run func(ctx context.Context, job *entity.Job)) *MockJobRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Job
		if args[1] != nil {
			arg1 = args[1].(*entity.Job)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJobRepository_Create_Call) Return(err error) *MockJobRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockJobRepository_Create_Call) RunAndReturn(run func(ctx context.Context, job *entity.Job) error) *MockJobRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockJobRepository
func (_mock *MockJobRepository) GetByID(ctx context.Context, id uuid.UUID) (*entity.Job, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Job, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Job); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJobRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockJobRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockJobRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockJobRepository_GetByID_Call {
	return &MockJobRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockJobRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockJobRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJobRepository_GetByID_Call) Return(job *entity.Job, err error) *MockJobRepository_GetByID_Call {
	_c.Call.Return(job, err)
	return _c
}

func (_c *MockJobRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*entity.Job, error)) *MockJobRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetBySQSMessageID provides a mock function for the type MockJobRepository
func (_mock *MockJobRepository) GetBySQSMessageID(ctx context.Context, sqsMessageID string) (*entity.Job, error) {
	ret := _mock.Called(ctx, sqsMessageID)

	if len(ret) == 0 {
		panic("no return value specified for GetBySQSMessageID")
	}

	var r0 *entity.Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.Job, error)); ok {
		return returnFunc(ctx, sqsMessageID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.Job); ok {
		r0 = returnFunc(ctx, sqsMessageID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, sqsMessageID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJobRepository_GetBySQSMessageID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBySQSMessageID'
type MockJobRepository_GetBySQSMessageID_Call struct {
	*mock.Call
}

// GetBySQSMessageID is a helper method to define mock.On call
//   - ctx context.Context
//   - sqsMessageID string
func (_e *MockJobRepository_Expecter) GetBySQSMessageID(ctx interface{}, sqsMessageID interface{}) *MockJobRepository_GetBySQSMessageID_Call {
	return &MockJobRepository_GetBySQSMessageID_Call{Call: _e.mock.On("GetBySQSMessageID", ctx, sqsMessageID)}
}

func (_c *MockJobRepository_GetBySQSMessageID_Call) Run(run func(ctx context.Context, sqsMessageID string)) *MockJobRepository_GetBySQSMessageID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJobRepository_GetBySQSMessageID_Call) Return(job *entity.Job, err error) *MockJobRepository_GetBySQSMessageID_Call {
	_c.Call.Return(job, err)
	return _c
}

func (_c *MockJobRepository_GetBySQSMessageID_Call) RunAndReturn(run func(ctx context.Context, sqsMessageID string) (*entity.Job, error)) *MockJobRepository_GetBySQSMessageID_Call {
	_c.Call.Return(run)
	return _c
}

// GetJobsByStatus provides a mock function for the type MockJobRepository
func (_mock *MockJobRepository) GetJobsByStatus(ctx context.Context, status job.Status, limit int) ([]*entity.Job, error) {
	ret := _mock.Called(ctx, status, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetJobsByStatus")
	}

	var r0 []*entity.Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, job.Status, int) ([]*entity.Job, error)); ok {
		return returnFunc(ctx, status, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, job.Status, int) []*entity.Job); ok {
		r0 = returnFunc(ctx, status, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, job.Status, int) error); ok {
		r1 = returnFunc(ctx, status, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJobRepository_GetJobsByStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJobsByStatus'
type MockJobRepository_GetJobsByStatus_Call struct {
	*mock.Call
}

// GetJobsByStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - status job.Status
//   - limit int
func (_e *MockJobRepository_Expecter) GetJobsByStatus(ctx interface{}, status interface{}, limit interface{}) *MockJobRepository_GetJobsByStatus_Call {
	return &MockJobRepository_GetJobsByStatus_Call{Call: _e.mock.On("GetJobsByStatus", ctx, status, limit)}
}

func (_c *MockJobRepository_GetJobsByStatus_Call) Run(run func(ctx context.Context, status job.Status, limit int)) *MockJobRepository_GetJobsByStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 job.Status
		if args[1] != nil {
			arg1 = args[1].(job.Status)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockJobRepository_GetJobsByStatus_Call) Return(jobs []*entity.Job, err error) *MockJobRepository_GetJobsByStatus_Call {
	_c.Call.Return(jobs, err)
	return _c
}

func (_c *MockJobRepository_GetJobsByStatus_Call) RunAndReturn(run func(ctx context.Context, status job.Status, limit int) ([]*entity.Job, error)) *MockJobRepository_GetJobsByStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetPendingJobs provides a mock function for the type MockJobRepository
func (_mock *MockJobRepository) GetPendingJobs(ctx context.Context, limit int) ([]*entity.Job, error) {
	ret := _mock.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingJobs")
	}

	var r0 []*entity.Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]*entity.Job, error)); ok {
		return returnFunc(ctx, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []*entity.Job); ok {
		r0 = returnFunc(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJobRepository_GetPendingJobs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPendingJobs'
type MockJobRepository_GetPendingJobs_Call struct {
	*mock.Call
}

// GetPendingJobs is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *MockJobRepository_Expecter) GetPendingJobs(ctx interface{}, limit interface{}) *MockJobRepository_GetPendingJobs_Call {
	return &MockJobRepository_GetPendingJobs_Call{Call: _e.mock.On("GetPendingJobs", ctx, limit)}
}

func (_c *MockJobRepository_GetPendingJobs_Call) Run(run func(ctx context.Context, limit int)) *MockJobRepository_GetPendingJobs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJobRepository_GetPendingJobs_Call) Return(jobs []*entity.Job, err error) *MockJobRepository_GetPendingJobs_Call {
	_c.Call.Return(jobs, err)
	return _c
}

func (_c *MockJobRepository_GetPendingJobs_Call) RunAndReturn(run func(ctx context.Context, limit int) ([]*entity.Job, error)) *MockJobRepository_GetPendingJobs_Call {
	_c.Call.Return(run)
	return _c
}

// GetRetryableJobs provides a mock function for the type MockJobRepository
func (_mock *MockJobRepository) GetRetryableJobs(ctx context.Context, beforeTime time.Time, limit int) ([]*entity.Job, error) {
	ret := _mock.Called(ctx, beforeTime, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetRetryableJobs")
	}

	var r0 []*entity.Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, int) ([]*entity.Job, error)); ok {
		return returnFunc(ctx, beforeTime, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, int) []*entity.Job); ok {
		r0 = returnFunc(ctx, beforeTime, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time, int) error); ok {
		r1 = returnFunc(ctx, beforeTime, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJobRepository_GetRetryableJobs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRetryableJobs'
type MockJobRepository_GetRetryableJobs_Call struct {
	*mock.Call
}

// GetRetryableJobs is a helper method to define mock.On call
//   - ctx context.Context
//   - beforeTime time.Time
//   - limit int
func (_e *MockJobRepository_Expecter) GetRetryableJobs(ctx interface{}, beforeTime interface{}, limit interface{}) *MockJobRepository_GetRetryableJobs_Call {
	return &MockJobRepository_GetRetryableJobs_Call{Call: _e.mock.On("GetRetryableJobs", ctx, beforeTime, limit)}
}

func (_c *MockJobRepository_GetRetryableJobs_Call) Run(run func(ctx context.Context, beforeTime time.Time, limit int)) *MockJobRepository_GetRetryableJobs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockJobRepository_GetRetryableJobs_Call) Return(jobs []*entity.Job, err error) *MockJobRepository_GetRetryableJobs_Call {
	_c.Call.Return(jobs, err)
	return _c
}

func (_c *MockJobRepository_GetRetryableJobs_Call) RunAndReturn(run func(ctx context.Context, beforeTime time.Time, limit int) ([]*entity.Job, error)) *MockJobRepository_GetRetryableJobs_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementAttempts provides a mock function for the type MockJobRepository
func (_mock *MockJobRepository) IncrementAttempts(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for IncrementAttempts")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockJobRepository_IncrementAttempts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementAttempts'
type MockJobRepository_IncrementAttempts_Call struct {
	*mock.Call
}

// IncrementAttempts is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockJobRepository_Expecter) IncrementAttempts(ctx interface{}, id interface{}) *MockJobRepository_IncrementAttempts_Call {
	return &MockJobRepository_IncrementAttempts_Call{Call: _e.mock.On("IncrementAttempts", ctx, id)}
}

func (_c *MockJobRepository_IncrementAttempts_Call) Run(run func(ctx context.Context, id string)) *MockJobRepository_IncrementAttempts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJobRepository_IncrementAttempts_Call) Return(err error) *MockJobRepository_IncrementAttempts_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockJobRepository_IncrementAttempts_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockJobRepository_IncrementAttempts_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCompleteTime provides a mock function for the type MockJobRepository
func (_mock *MockJobRepository) UpdateCompleteTime(ctx context.Context, id string, completedAt time.Time) error {
	ret := _mock.Called(ctx, id, completedAt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCompleteTime")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = returnFunc(ctx, id, completedAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockJobRepository_UpdateCompleteTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCompleteTime'
type MockJobRepository_UpdateCompleteTime_Call struct {
	*mock.Call
}

// UpdateCompleteTime is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - completedAt time.Time
func (_e *MockJobRepository_Expecter) UpdateCompleteTime(ctx interface{}, id interface{}, completedAt interface{}) *MockJobRepository_UpdateCompleteTime_Call {
	return &MockJobRepository_UpdateCompleteTime_Call{Call: _e.mock.On("UpdateCompleteTime", ctx, id, completedAt)}
}

func (_c *MockJobRepository_UpdateCompleteTime_Call) Run(run func(ctx context.Context, id string, completedAt time.Time)) *MockJobRepository_UpdateCompleteTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockJobRepository_UpdateCompleteTime_Call) Return(err error) *MockJobRepository_UpdateCompleteTime_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockJobRepository_UpdateCompleteTime_Call) RunAndReturn(run func(ctx context.Context, id string, completedAt time.Time) error) *MockJobRepository_UpdateCompleteTime_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateJobToCompleted provides a mock function for the type MockJobRepository
func (_mock *MockJobRepository) UpdateJobToCompleted(ctx context.Context, id string, completedAt time.Time) error {
	ret := _mock.Called(ctx, id, completedAt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateJobToCompleted")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = returnFunc(ctx, id, completedAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockJobRepository_UpdateJobToCompleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateJobToCompleted'
type MockJobRepository_UpdateJobToCompleted_Call struct {
	*mock.Call
}

// UpdateJobToCompleted is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - completedAt time.Time
func (_e *MockJobRepository_Expecter) UpdateJobToCompleted(ctx interface{}, id interface{}, completedAt interface{}) *MockJobRepository_UpdateJobToCompleted_Call {
	return &MockJobRepository_UpdateJobToCompleted_Call{Call: _e.mock.On("UpdateJobToCompleted", ctx, id, completedAt)}
}

func (_c *MockJobRepository_UpdateJobToCompleted_Call) Run(run func(ctx context.Context, id string, completedAt time.Time)) *MockJobRepository_UpdateJobToCompleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockJobRepository_UpdateJobToCompleted_Call) Return(err error) *MockJobRepository_UpdateJobToCompleted_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockJobRepository_UpdateJobToCompleted_Call) RunAndReturn(run func(ctx context.Context, id string, completedAt time.Time) error) *MockJobRepository_UpdateJobToCompleted_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateJobToFailed provides a mock function for the type MockJobRepository
func (_mock *MockJobRepository) UpdateJobToFailed(ctx context.Context, id string, errorMsg string) error {
	ret := _mock.Called(ctx, id, errorMsg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateJobToFailed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, id, errorMsg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockJobRepository_UpdateJobToFailed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateJobToFailed'
type MockJobRepository_UpdateJobToFailed_Call struct {
	*mock.Call
}

// UpdateJobToFailed is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - errorMsg string
func (_e *MockJobRepository_Expecter) UpdateJobToFailed(ctx interface{}, id interface{}, errorMsg interface{}) *MockJobRepository_UpdateJobToFailed_Call {
	return &MockJobRepository_UpdateJobToFailed_Call{Call: _e.mock.On("UpdateJobToFailed", ctx, id, errorMsg)}
}

func (_c *MockJobRepository_UpdateJobToFailed_Call) Run(run func(ctx context.Context, id string, errorMsg string)) *MockJobRepository_UpdateJobToFailed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockJobRepository_UpdateJobToFailed_Call) Return(err error) *MockJobRepository_UpdateJobToFailed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockJobRepository_UpdateJobToFailed_Call) RunAndReturn(run func(ctx context.Context, id string, errorMsg string) error) *MockJobRepository_UpdateJobToFailed_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateJobToProcessing provides a mock function for the type MockJobRepository
func (_mock *MockJobRepository) UpdateJobToProcessing(ctx context.Context, id string, startedAt time.Time) error {
	ret := _mock.Called(ctx, id, startedAt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateJobToProcessing")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = returnFunc(ctx, id, startedAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockJobRepository_UpdateJobToProcessing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateJobToProcessing'
type MockJobRepository_UpdateJobToProcessing_Call struct {
	*mock.Call
}

// UpdateJobToProcessing is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - startedAt time.Time
func (_e *MockJobRepository_Expecter) UpdateJobToProcessing(ctx interface{}, id interface{}, startedAt interface{}) *MockJobRepository_UpdateJobToProcessing_Call {
	return &MockJobRepository_UpdateJobToProcessing_Call{Call: _e.mock.On("UpdateJobToProcessing", ctx, id, startedAt)}
}

func (_c *MockJobRepository_UpdateJobToProcessing_Call) Run(run func(ctx context.Context, id string, startedAt time.Time)) *MockJobRepository_UpdateJobToProcessing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockJobRepository_UpdateJobToProcessing_Call) Return(err error) *MockJobRepository_UpdateJobToProcessing_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockJobRepository_UpdateJobToProcessing_Call) RunAndReturn(run func(ctx context.Context, id string, startedAt time.Time) error) *MockJobRepository_UpdateJobToProcessing_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateJobToRetrying provides a mock function for the type MockJobRepository
func (_mock *MockJobRepository) UpdateJobToRetrying(ctx context.Context, id string, errorMsg string) error {
	ret := _mock.Called(ctx, id, errorMsg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateJobToRetrying")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, id, errorMsg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockJobRepository_UpdateJobToRetrying_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateJobToRetrying'
type MockJobRepository_UpdateJobToRetrying_Call struct {
	*mock.Call
}

// UpdateJobToRetrying is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - errorMsg string
func (_e *MockJobRepository_Expecter) UpdateJobToRetrying(ctx interface{}, id interface{}, errorMsg interface{}) *MockJobRepository_UpdateJobToRetrying_Call {
	return &MockJobRepository_UpdateJobToRetrying_Call{Call: _e.mock.On("UpdateJobToRetrying", ctx, id, errorMsg)}
}

func (_c *MockJobRepository_UpdateJobToRetrying_Call) Run(run func(ctx context.Context, id string, errorMsg string)) *MockJobRepository_UpdateJobToRetrying_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockJobRepository_UpdateJobToRetrying_Call) Return(err error) *MockJobRepository_UpdateJobToRetrying_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockJobRepository_UpdateJobToRetrying_Call) RunAndReturn(run func(ctx context.Context, id string, errorMsg string) error) *MockJobRepository_UpdateJobToRetrying_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStartTime provides a mock function for the type MockJobRepository
func (_mock *MockJobRepository) UpdateStartTime(ctx context.Context, id string, startedAt time.Time) error {
	ret := _mock.Called(ctx, id, startedAt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStartTime")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = returnFunc(ctx, id, startedAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockJobRepository_UpdateStartTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStartTime'
type MockJobRepository_UpdateStartTime_Call struct {
	*mock.Call
}

// UpdateStartTime is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - startedAt time.Time
func (_e *MockJobRepository_Expecter) UpdateStartTime(ctx interface{}, id interface{}, startedAt interface{}) *MockJobRepository_UpdateStartTime_Call {
	return &MockJobRepository_UpdateStartTime_Call{Call: _e.mock.On("UpdateStartTime", ctx, id, startedAt)}
}

func (_c *MockJobRepository_UpdateStartTime_Call) Run(run func(ctx context.Context, id string, startedAt time.Time)) *MockJobRepository_UpdateStartTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockJobRepository_UpdateStartTime_Call) Return(err error) *MockJobRepository_UpdateStartTime_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockJobRepository_UpdateStartTime_Call) RunAndReturn(run func(ctx context.Context, id string, startedAt time.Time) error) *MockJobRepository_UpdateStartTime_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function for the type MockJobRepository
func (_mock *MockJobRepository) UpdateStatus(ctx context.Context, id string, status job.Status, error1 string) error {
	ret := _mock.Called(ctx, id, status, error1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, job.Status, string) error); ok {
		r0 = returnFunc(ctx, id, status, error1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockJobRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockJobRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - status job.Status
//   - error1 string
func (_e *MockJobRepository_Expecter) UpdateStatus(ctx interface{}, id interface{}, status interface{}, error1 interface{}) *MockJobRepository_UpdateStatus_Call {
	return &MockJobRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, id, status, error1)}
}

func (_c *MockJobRepository_UpdateStatus_Call) Run(run func(ctx context.Context, id string, status job.Status, error1 string)) *MockJobRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 job.Status
		if args[2] != nil {
			arg2 = args[2].(job.Status)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockJobRepository_UpdateStatus_Call) Return(err error) *MockJobRepository_UpdateStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockJobRepository_UpdateStatus_Call) RunAndReturn(run func(ctx context.Context, id string, status job.Status, error1 string) error) *MockJobRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}
